# 01.5 — NumPy

**Phase:** 01 — Python Foundations

**Status:** VERIFIED

---

## 1. What Are We Solving?

Python lists are slow and don't support element-wise math. **NumPy** provides fast, vectorized arrays that are the foundation of all scientific computing in Python — and the backbone of Pandas, scikit-learn, and PyTorch.

## 2. Why Does This Matter?

Almost every ML operation (matrix multiplication, broadcasting, reshaping) is done with NumPy. Understanding NumPy is essential for data manipulation and for understanding how ML libraries work under the hood.

## 3. Prerequisites

- Unit 01.1 (Python basics)
- Unit 01.2 (Data structures)

## 4. Learning Objectives

By the end of this notebook, you should be able to:
- Create NumPy arrays
- Use array attributes (shape, dtype, ndim)
- Index and slice arrays
- Use vectorized operations
- Use broadcasting
- Use universal functions (ufuncs)
- Perform matrix operations
- Use aggregation functions

## 5. Mental Model

A NumPy array is a **grid of numbers** with a fixed shape. Unlike lists, operations apply **element-wise** automatically (vectorization), which is both faster and more concise. Think of it as a spreadsheet where every cell operation happens at once.

## 6. Creating Arrays

NumPy arrays can be created from lists, or with built-in functions.

In [1]:
import numpy as np

# From a list
a = np.array([1, 2, 3, 4, 5])
print(f"a: {a}")

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(f"b:\n{b}")

# Built-in creators
zeros = np.zeros((2, 3))
ones = np.ones((3,))
eye = np.eye(3)
arange = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)

print(f"zeros:\n{zeros}")
print(f"ones: {ones}")
print(f"eye:\n{eye}")
print(f"arange: {arange}")
print(f"linspace: {linspace}")

a: [1 2 3 4 5]
b:
[[1 2 3]
 [4 5 6]]
zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
ones: [1. 1. 1.]
eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


## 7. Array Attributes

Every array has attributes describing its shape, size, and data type.

In [2]:
# Array attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"arr:\n{arr}")
print(f"shape: {arr.shape}")   # (rows, cols)
print(f"ndim: {arr.ndim}")     # number of dimensions
print(f"size: {arr.size}")     # total elements
print(f"dtype: {arr.dtype}")   # data type
print(f"nbytes: {arr.nbytes}") # bytes used

arr:
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
size: 6
dtype: int64
nbytes: 48


## 8. Indexing and Slicing

NumPy supports the same indexing/slicing as lists, plus multi-dimensional indexing.

In [3]:
# Indexing and slicing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"arr:\n{arr}")
print(f"arr[0]: {arr[0]}")          # first row
print(f"arr[0, 1]: {arr[0, 1]}")    # row 0, col 1
print(f"arr[:, 0]: {arr[:, 0]}")    # first column
print(f"arr[1:, :2]:\n{arr[1:, :2]}")  # rows 1+, cols 0-1
print(f"arr[-1]: {arr[-1]}")        # last row

arr:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr[0]: [1 2 3]
arr[0, 1]: 2
arr[:, 0]: [1 4 7]
arr[1:, :2]:
[[4 5]
 [7 8]]
arr[-1]: [7 8 9]


In [4]:
# Boolean masking
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(f"mask: {mask}")
print(f"arr[mask]: {arr[mask]}")
print(f"arr[arr % 2 == 0]: {arr[arr % 2 == 0]}")  # even numbers

mask: [False False False  True  True  True]
arr[mask]: [4 5 6]
arr[arr % 2 == 0]: [2 4 6]


## 9. Vectorized Operations

Operations apply element-wise automatically — no loops needed.

In [5]:
# Vectorized operations
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"a + b: {a + b}")
print(f"a * b: {a * b}")
print(f"a - b: {a - b}")
print(f"a / b: {a / b}")
print(f"a ** 2: {a ** 2}")
print(f"np.sqrt(a): {np.sqrt(a)}")
print(f"np.exp(a): {np.exp(a)}")
print(f"np.log(a): {np.log(a)}")

a + b: [11 22 33 44]
a * b: [ 10  40  90 160]
a - b: [ -9 -18 -27 -36]
a / b: [0.1 0.1 0.1 0.1]
a ** 2: [ 1  4  9 16]
np.sqrt(a): [1.         1.41421356 1.73205081 2.        ]
np.exp(a): [ 2.71828183  7.3890561  20.08553692 54.59815003]
np.log(a): [0.         0.69314718 1.09861229 1.38629436]


## 10. Broadcasting

**Broadcasting** lets NumPy operate on arrays of different shapes by stretching the smaller one to match. This is a key concept for ML.

In [6]:
# Broadcasting
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"arr:\n{arr}")

# Add a scalar to every element
print(f"arr + 10:\n{arr + 10}")

# Add a 1D row vector to each row
row = np.array([10, 20, 30])
print(f"arr + row:\n{arr + row}")

# Add a column vector to each column
col = np.array([[100], [200]])
print(f"arr + col:\n{arr + col}")

arr:
[[1 2 3]
 [4 5 6]]
arr + 10:
[[11 12 13]
 [14 15 16]]
arr + row:
[[11 22 33]
 [14 25 36]]
arr + col:
[[101 102 103]
 [204 205 206]]


## 11. Matrix Operations

Matrix multiplication is central to ML (weights × inputs).

In [7]:
# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"A:\n{A}")
print(f"B:\n{B}")

# Matrix multiplication (dot product)
print(f"A @ B:\n{A @ B}")
print(f"np.dot(A, B):\n{np.dot(A, B)}")

# Element-wise multiplication
print(f"A * B (element-wise):\n{A * B}")

# Transpose
print(f"A.T:\n{A.T}")

# Inverse
print(f"np.linalg.inv(A):\n{np.linalg.inv(A)}")

A:
[[1 2]
 [3 4]]


B:
[[5 6]
 [7 8]]
A @ B:
[[19 22]
 [43 50]]
np.dot(A, B):
[[19 22]
 [43 50]]
A * B (element-wise):
[[ 5 12]
 [21 32]]
A.T:
[[1 3]
 [2 4]]
np.linalg.inv(A):
[[-2.   1. ]
 [ 1.5 -0.5]]


## 12. Aggregations

NumPy provides fast aggregation functions.

In [8]:
# Aggregations
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"arr:\n{arr}")
print(f"sum: {arr.sum()}")
print(f"mean: {arr.mean()}")
print(f"std: {arr.std():.3f}")
print(f"min: {arr.min()}, max: {arr.max()}")
print(f"sum along axis 0 (columns): {arr.sum(axis=0)}")
print(f"sum along axis 1 (rows): {arr.sum(axis=1)}")
print(f"mean along axis 0: {arr.mean(axis=0)}")

arr:
[[1 2 3]
 [4 5 6]]
sum: 21
mean: 3.5
std: 1.708
min: 1, max: 6
sum along axis 0 (columns): [5 7 9]
sum along axis 1 (rows): [ 6 15]
mean along axis 0: [2.5 3.5 4.5]


## 13. Reshaping

Reshaping changes the shape without changing the data.

In [9]:
# Reshaping
arr = np.arange(12)
print(f"arr: {arr}")

reshaped = arr.reshape(3, 4)
print(f"reshaped (3,4):\n{reshaped}")

flattened = reshaped.flatten()
print(f"flattened: {flattened}")

# Reshape with -1 (infer dimension)
auto = arr.reshape(2, -1)
print(f"reshape(2, -1):\n{auto}")

arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped (3,4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape(2, -1):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## 14. Experiment: Linear Regression with NumPy

Let's solve linear regression using the **normal equation**: `w = (X^T X)^-1 X^T y`. This is a real ML computation done entirely with NumPy.

In [10]:
# Linear regression with the normal equation
np.random.seed(42)

# Generate data: y = 2x + 3 + noise
X = np.random.rand(100, 1) * 10
true_slope, true_intercept = 2.0, 3.0
y = true_slope * X + true_intercept + np.random.randn(100, 1) * 0.5

# Add bias column (column of ones)
X_b = np.c_[np.ones((100, 1)), X]

# Normal equation: w = (X^T X)^-1 X^T y
w = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

print(f"Learned intercept: {w[0, 0]:.3f} (true: 3.0)")
print(f"Learned slope: {w[1, 0]:.3f} (true: 2.0)")

# Predictions
y_pred = X_b @ w
mse = np.mean((y - y_pred) ** 2)
print(f"MSE: {mse:.4f}")

Learned intercept: 3.108 (true: 3.0)
Learned slope: 1.977 (true: 2.0)
MSE: 0.2016


## 15. Failure Case: Shape Mismatch

A common error is trying to multiply arrays with incompatible shapes.

In [11]:
# Shape mismatch error
a = np.array([1, 2, 3])       # shape (3,)
b = np.array([[1, 2], [3, 4]])  # shape (2, 2)

try:
    result = a @ b
except ValueError as e:
    print(f"ValueError: {e}")
    print("Fix: shapes must be compatible for matrix multiplication.")
    print(f"a.shape: {a.shape}, b.shape: {b.shape}")
    print("a @ b requires a.shape[1] == b.shape[0] (or broadcasting rules)")

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
Fix: shapes must be compatible for matrix multiplication.
a.shape: (3,), b.shape: (2, 2)
a @ b requires a.shape[1] == b.shape[0] (or broadcasting rules)


## 16. Debugging: Common Errors

### Shape mismatch
```python
np.array([1,2,3]) @ np.array([[1,2],[3,4]])  # ValueError
```

### Broadcasting error
```python
np.ones((3,3)) + np.ones((2,2))  # ValueError
```

### dtype issues
```python
np.array([1,2,3]) / 2  # float result, not int
```

### In-place vs new array
```python
a = np.array([1,2,3])
b = a  # b is a VIEW, not a copy!
b[0] = 99  # modifies a too
```
Use `.copy()` to avoid this.

In [12]:
# Demonstrate view vs copy
a = np.array([1, 2, 3])
b = a          # view (same data)
c = a.copy()   # independent copy

b[0] = 99
print(f"a after modifying b: {a}")  # a changed! (view)
print(f"c: {c}")                    # c unchanged (copy)
print("Use .copy() when you need an independent array.")

a after modifying b: [99  2  3]


c: [1 2 3]
Use .copy() when you need an independent array.


## 17. Real-World Considerations

- **Vectorize**: avoid Python loops over arrays — use NumPy operations.
- **dtype matters**: use `float32`/`float64` appropriately (memory vs precision).
- **Views vs copies**: be aware that slicing returns views, not copies.
- **Random seed**: use `np.random.seed()` for reproducible experiments.
- **Broadcasting**: understand it — it's everywhere in ML.

## 18. Common Mistakes

- Confusing `*` (element-wise) with `@` (matrix multiply)
- Shape mismatches
- Modifying views thinking they're copies
- Using Python loops instead of vectorized ops
- Forgetting the bias term in linear models

## 19. When NOT to Use

- Don't use NumPy for small, simple data — Python lists are fine.
- Don't use NumPy when you need labeled columns — use Pandas.
- Don't use NumPy for deep learning — use PyTorch (GPU support).

## 20. Challenge

Create a 5×5 array of random integers 0–9. Then:
1. Compute the mean of each row.
2. Find the maximum value in the whole array.
3. Replace all values greater than 5 with 0.

In [13]:
# Challenge: random array operations
np.random.seed(7)
arr = np.random.randint(0, 10, size=(5, 5))
print(f"arr:\n{arr}")

row_means = arr.mean(axis=1)
print(f"row means: {row_means}")

max_val = arr.max()
print(f"max value: {max_val}")

arr[arr > 5] = 0
print(f"after replacing >5 with 0:\n{arr}")

arr:
[[4 9 6 3 3]
 [7 7 9 7 8]
 [9 8 7 6 4]
 [0 7 0 7 6]
 [3 5 8 8 7]]
row means: [5.  7.6 6.8 4.  6.2]
max value: 9
after replacing >5 with 0:
[[4 0 0 3 3]
 [0 0 0 0 0]
 [0 0 0 0 4]
 [0 0 0 0 0]
 [3 5 0 0 0]]


## 21. Closed-Book Recall

Without looking back:

1. How do you create a 3×3 array of zeros?
2. What's the difference between `*` and `@` on arrays?
3. What is broadcasting?
4. How do you get the shape of an array?
5. What's the difference between a view and a copy?

## 22. Teach-Back Questions

Explain to another person:

- What is vectorization and why is it fast?
- What is broadcasting?
- How does the normal equation solve linear regression?

## 23. Summary

You now understand NumPy arrays, vectorization, broadcasting, matrix operations, and aggregations. This is the foundation for Pandas and all of ML.

## 24. Further Experiment

- Implement a simple neural network layer (weights @ inputs + bias) with NumPy.
- Compute the dot product of two vectors manually and with `@`.
- Explore `np.random` distributions (normal, uniform, binomial).

## 25. Verification Status

```
STATUS: VERIFIED
EXECUTION: PASS
DEPENDENCIES: numpy
OUTPUTS: PASS
LAST VERIFIED: 2026-08-28
```