# 01.5 — NumPy

**Phase:** 01 — Python Foundations  
**Difficulty:** Intermediate  
**Priority:** Critical — the foundation of all numerical ML

---

## What Are We Solving?

Python lists are slow and don't support element-wise math. If you try to multiply two lists, Python concatenates them instead of doing math.

**NumPy** provides fast, vectorized arrays that are the foundation of all scientific computing in Python — and the backbone of Pandas, scikit-learn, and PyTorch.

## Why Does It Matter?

Almost every ML operation is done with NumPy:
- **Training** a model = matrix operations on NumPy arrays
- **Data preprocessing** = vectorized transformations
- **Evaluation** = fast aggregations over arrays

## Mental Model

A NumPy array is a **grid of numbers** with a fixed shape. Operations apply **element-wise** automatically (vectorization).

```
Python list:  [1,2,3] + [4,5,6] = [1,2,3,4,5,6]  # concatenated!
NumPy array:  [1,2,3] + [4,5,6] = [5,7,9]          # element-wise!
```

## Prerequisites

- [ ] 01.1 — Python Basics
- [ ] 01.2 — Data Structures

## Learning Objectives

By the end of this notebook, you should be able to:

- [ ] Create NumPy arrays from lists and with built-in functions
- [ ] Use array attributes (shape, dtype, ndim, size)
- [ ] Index and slice arrays (including multi-dimensional)
- [ ] Use vectorized operations (element-wise math)
- [ ] Understand and apply broadcasting
- [ ] Perform matrix operations (@, dot, transpose, inverse)
- [ ] Use aggregation functions (sum, mean, std, min, max)

---

## Creating Arrays

| Function | What it creates | Example |
|----------|----------------|---------|
| `np.array(list)` | From a Python list | `np.array([1, 2, 3])` |
| `np.zeros((r, c))` | Array of zeros | `np.zeros((2, 3))` |
| `np.ones((n,))` | Array of ones | `np.ones((3,))` |
| `np.eye(n)` | Identity matrix | `np.eye(3)` |
| `np.arange(s, stop, step)` | Range | `np.arange(0, 10, 2)` |
| `np.linspace(s, stop, num)` | Evenly spaced | `np.linspace(0, 1, 5)` |
| `np.random.rand(...)` | Random | `np.random.rand(3, 3)` |

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(f"a: {a}")

b = np.array([[1, 2, 3], [4, 5, 6]])
print(f"b:\n{b}")

zeros = np.zeros((2, 3))
ones = np.ones((3,))
eye = np.eye(3)
arange = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)

print(f"zeros:\n{zeros}")
print(f"ones: {ones}")
print(f"eye:\n{eye}")
print(f"arange: {arange}")
print(f"linspace: {linspace}")

---

## Array Attributes

| Attribute | What it returns | Example |
|-----------|----------------|---------|
| `.shape` | Dimensions as tuple | `(2, 3)` for 2 rows, 3 cols |
| `.ndim` | Number of dimensions | `2` for a 2D array |
| `.size` | Total elements | `6` for a 2×3 array |
| `.dtype` | Data type | `int64`, `float64` |
| `.nbytes` | Memory in bytes | `48` for 6 int64 values |

**ML relevance:** Shape mismatches are the #1 source of errors in ML code. Always check `.shape` when debugging.

In [1]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"arr:\n{arr}")
print(f"shape: {arr.shape}")
print(f"ndim: {arr.ndim}")
print(f"size: {arr.size}")
print(f"dtype: {arr.dtype}")
print(f"nbytes: {arr.nbytes}")

a: [1 2 3 4 5]
b:
[[1 2 3]
 [4 5 6]]
zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
ones: [1. 1. 1.]
eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


---

## Indexing and Slicing

```
arr = [[1, 2, 3],    # row 0
       [4, 5, 6],    # row 1
       [7, 8, 9]]    # row 2

arr[0]        -> [1, 2, 3]      # first row
arr[0, 1]     -> 2              # row 0, col 1
arr[:, 0]     -> [1, 4, 7]      # first column
arr[1:, :2]   -> [[4, 5],       # rows 1+, cols 0-1
                  [7, 8]]
```

**Key insight:** In 2D arrays, `arr[i]` selects a row. Use `arr[i, j]` for a specific element.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"arr:\n{arr}")
print(f"arr[0]: {arr[0]}")
print(f"arr[0, 1]: {arr[0, 1]}")
print(f"arr[:, 0]: {arr[:, 0]}")
print(f"arr[1:, :2]:\n{arr[1:, :2]}")
print(f"arr[-1]: {arr[-1]}")

### Boolean Masking

```python
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3       # [False, False, False, True, True, True]
arr[mask]            # [4, 5, 6]
arr[arr % 2 == 0]    # [2, 4, 6] — even numbers
```

**ML relevance:** This is how you filter data — selecting samples where a feature meets a condition.

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(f"mask: {mask}")
print(f"arr[mask]: {arr[mask]}")
print(f"arr[arr % 2 == 0]: {arr[arr % 2 == 0]}")

arr:
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
size: 6
dtype: int64
nbytes: 48


---

## Vectorized Operations

| Operation | Syntax | Notes |
|-----------|--------|-------|
| Addition | `a + b` | Element-wise sum |
| Multiplication | `a * b` | Element-wise (NOT matrix multiply!) |
| Power | `a ** 2` | Element-wise square |
| Square root | `np.sqrt(a)` | Element-wise sqrt |
| Exponential | `np.exp(a)` | Element-wise e^x |
| Logarithm | `np.log(a)` | Element-wise natural log |

**Warning:** `*` is element-wise. For matrix multiplication, use `@` or `np.dot()`.

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"a + b: {a + b}")
print(f"a * b: {a * b}")
print(f"a - b: {a - b}")
print(f"a / b: {a / b}")
print(f"a ** 2: {a ** 2}")
print(f"np.sqrt(a): {np.sqrt(a)}")
print(f"np.exp(a): {np.exp(a)}")
print(f"np.log(a): {np.log(a)}")

---

## Broadcasting

**Broadcasting** lets NumPy operate on arrays of different shapes by stretching the smaller one to match.

```python
arr = [[1, 2, 3], [4, 5, 6]]  # shape (2, 3)
arr + 10             # scalar broadcasts to every element
arr + [10, 20, 30]   # row vector broadcasts to each row
arr + [[100], [200]]  # column vector broadcasts to each column
```

**Broadcasting rules:**
1. Pad smaller shape with 1s on the left
2. Size-1 dimensions stretch to match the largest
3. Incompatible shapes cause a ValueError

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"arr:\n{arr}")

print(f"arr + 10:\n{arr + 10}")

row = np.array([10, 20, 30])
print(f"arr + row:\n{arr + row}")

col = np.array([[100], [200]])
print(f"arr + col:\n{arr + col}")

arr:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr[0]: [1 2 3]
arr[0, 1]: 2
arr[:, 0]: [1 4 7]
arr[1:, :2]:
[[4 5]
 [7 8]]
arr[-1]: [7 8 9]


---

## Matrix Operations

| Operation | Syntax | Notes |
|-----------|--------|-------|
| Matrix multiply | `A @ B` or `np.dot(A, B)` | Cols of A must match rows of B |
| Element-wise | `A * B` | Same shape required |
| Transpose | `A.T` | Swap rows and columns |
| Inverse | `np.linalg.inv(A)` | A must be square and invertible |

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"A:\n{A}")
print(f"B:\n{B}")
print(f"A @ B:\n{A @ B}")
print(f"np.dot(A, B):\n{np.dot(A, B)}")
print(f"A * B (element-wise):\n{A * B}")
print(f"A.T:\n{A.T}")
print(f"np.linalg.inv(A):\n{np.linalg.inv(A)}")

mask: [False False False  True  True  True]
arr[mask]: [4 5 6]
arr[arr % 2 == 0]: [2 4 6]


---

## Aggregations

| Function | axis=None | axis=0 | axis=1 |
|----------|-----------|--------|--------|
| `.sum()` | Total sum | Sum each column | Sum each row |
| `.mean()` | Global mean | Mean of each col | Mean of each row |
| `.std()` | Global std | Std of each col | Std of each row |
| `.min()` | Global min | Min of each col | Min of each row |
| `.max()` | Global max | Max of each col | Max of each row |

**ML relevance:** Normalization involves `X.mean(axis=0)` and `X.std(axis=0)`.

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"arr:\n{arr}")
print(f"sum: {arr.sum()}")
print(f"mean: {arr.mean()}")
print(f"std: {arr.std():.3f}")
print(f"min: {arr.min()}, max: {arr.max()}")
print(f"sum axis 0 (columns): {arr.sum(axis=0)}")
print(f"sum axis 1 (rows): {arr.sum(axis=1)}")
print(f"mean axis 0: {arr.mean(axis=0)}")

---

## Reshaping

| Method | What it does | Example |
|--------|-------------|---------|
| `.reshape(rows, cols)` | Change dimensions | `arr.reshape(3, 4)` |
| `.flatten()` | 1D copy | `arr.flatten()` |
| `.ravel()` | 1D view (may share memory) | `arr.ravel()` |
| `.T` | Transpose (swap axes) | `arr.T` |

**Tip:** Use `-1` to infer a dimension: `arr.reshape(2, -1)` means "2 rows, figure out the columns."

In [5]:
arr = np.arange(12)
print(f"arr: {arr}")

reshaped = arr.reshape(3, 4)
print(f"reshaped (3,4):\n{reshaped}")

flattened = reshaped.flatten()
print(f"flattened: {flattened}")

auto = arr.reshape(2, -1)
print(f"reshape(2, -1):\n{auto}")

a + b: [11 22 33 44]
a * b: [ 10  40  90 160]
a - b: [ -9 -18 -27 -36]
a / b: [0.1 0.1 0.1 0.1]
a ** 2: [ 1  4  9 16]
np.sqrt(a): [1.         1.41421356 1.73205081 2.        ]
np.exp(a): [ 2.71828183  7.3890561  20.08553692 54.59815003]
np.log(a): [0.         0.69314718 1.09861229 1.38629436]


---

## Experiment: Linear Regression with NumPy

Let's solve linear regression using the **normal equation**: `w = (X^T X)^-1 X^T y`. This is a real ML computation done entirely with NumPy.

np.random.seed(42)

X = np.random.rand(100, 1) * 10
true_slope, true_intercept = 2.0, 3.0
y = true_slope * X + true_intercept + np.random.randn(100, 1) * 0.5

X_b = np.c_[np.ones((100, 1)), X]
w = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

print(f"Learned intercept: {w[0, 0]:.3f} (true: 3.0)")
print(f"Learned slope: {w[1, 0]:.3f} (true: 2.0)")

y_pred = X_b @ w
mse = np.mean((y - y_pred) ** 2)
print(f"MSE: {mse:.4f}")

---

## Common Mistakes

| Mistake | What goes wrong | How to fix it |
|---------|----------------|---------------|
| Confusing `*` with `@` | Element-wise vs matrix multiply | `*` = element-wise, `@` = matrix multiply |
| Shape mismatch | `ValueError: matmul: Input operand` | Check `.shape` — cols of A must match rows of B |
| Modifying views | Changing b changes a (same data) | Use `.copy()` for independent arrays |
| Python loops instead of vectorized | 100x slower | Use NumPy operations, not for loops |
| Forgetting bias term | Linear models miss the intercept | Add column of ones with `np.c_` |
| dtype issues | `int / int` returns float | Be aware of integer division with `//` |

In [6]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

try:
    result = a @ b
except ValueError as e:
    print(f"ValueError: {e}")
    print("Fix: shapes must be compatible for matrix multiplication.")
    print(f"a.shape: {a.shape}, b.shape: {b.shape}")

arr:
[[1 2 3]
 [4 5 6]]
arr + 10:
[[11 12 13]
 [14 15 16]]
arr + row:
[[11 22 33]
 [14 25 36]]
arr + col:
[[101 102 103]
 [204 205 206]]


a = np.array([1, 2, 3])
b = a          # view (same data)
c = a.copy()   # independent copy

b[0] = 99
print(f"a after modifying b: {a}")
print(f"c: {c}")
print("Use .copy() when you need an independent array.")

---

## Real-World Considerations

- **Vectorize**: avoid Python loops over arrays — use NumPy operations
- **dtype matters**: use `float32`/`float64` appropriately (memory vs precision)
- **Views vs copies**: be aware that slicing returns views, not copies
- **Random seed**: use `np.random.seed()` for reproducible experiments
- **Broadcasting**: understand it — it's everywhere in ML

---

## Hands-On Practice

### Level 1 — Basic
1. Create an array of numbers 0-9
2. Compute the sum, mean, and max

### Level 2 — Guided
1. Create a 3x3 identity matrix
2. Multiply it by 5
3. What do you get? Why?

### Level 3 — Independent
1. Create two 2x2 matrices
2. Compute A @ B and B @ A
3. Are they equal? Why or why not?

### Level 4 — Realistic
1. Generate 100 random data points: x = rand(100), y = 3*x + 2 + noise
2. Use the normal equation to recover the slope and intercept
3. Compare with the true values

### Level 5 — Challenge
Create a 5×5 array of random integers 0–9. Then:
1. Compute the mean of each row
2. Find the maximum value in the whole array
3. Replace all values greater than 5 with 0

In [7]:
np.random.seed(7)
arr = np.random.randint(0, 10, size=(5, 5))
print(f"arr:\n{arr}")

row_means = arr.mean(axis=1)
print(f"row means: {row_means}")

max_val = arr.max()
print(f"max value: {max_val}")

arr[arr > 5] = 0
print(f"after replacing >5 with 0:\n{arr}")

A:
[[1 2]
 [3 4]]


B:
[[5 6]
 [7 8]]
A @ B:
[[19 22]
 [43 50]]
np.dot(A, B):
[[19 22]
 [43 50]]
A * B (element-wise):
[[ 5 12]
 [21 32]]
A.T:
[[1 3]
 [2 4]]
np.linalg.inv(A):
[[-2.   1. ]
 [ 1.5 -0.5]]


---

## Knowledge Check

1. **How do you create a 3×3 array of zeros?** What dtype does it have by default?

2. **What's the difference between `*` and `@` on arrays?** Give an example of each.

3. **What is broadcasting?** Explain the three rules.

4. **How do you get the shape of an array?** Why is this important for debugging?

5. **What's the difference between a view and a copy?** How do you ensure you have a copy?

---

## Exit Criteria

You're ready to move on when you can:

- [ ] Create arrays from lists, zeros, ones, eye, arange, linspace
- [ ] Query array attributes (shape, ndim, size, dtype)
- [ ] Index and slice 1D and 2D arrays
- [ ] Apply boolean masks to filter elements
- [ ] Perform vectorized element-wise operations
- [ ] Explain and apply broadcasting
- [ ] Compute matrix products with `@` and `np.dot()`
- [ ] Use aggregation functions with axis parameter
- [ ] Reshape arrays with reshape, flatten, and -1
- [ ] Distinguish views from copies

If you checked all boxes, you're ready for **02 — Data Manipulation with Pandas**.

---

## Next Step

**→ 02 — Data Manipulation with Pandas**

NumPy handles raw numerical arrays. Pandas adds **labeled columns**, **missing data handling**, and **group-by operations** — the tools you need to clean and explore real datasets before feeding them to ML models.